### ISSUE TITLE
Grajenje URL-jev

### ISSUE THREAD

**Issue by jaanos** [ian-spiller/JIJ-prodaja-avtov#3]
Svetujem, da v svoj repozitorij dodaste še program [`bottleext.py`](https://github.com/jaanos/OPB-bottle/blob/master/bottleext.py) in iz njega uvažate namesto iz `bottle.py`. Tako bo mogoče grajenje URL-jev s funkcijo `url`, s čimer boste omogočili, da projekt teče tudi na Binderju. Za več podrobnosti si poglejte MatejRojec/Gamma#1.

Mimogrede, vidim, da na več mestih napake/opozorila prikazujete kar s HTML kodo, npr.
https://github.com/ian-spiller/JIJ-prodaja-avtov/blob/dc315aa385e12e4ffb6c9e57e80e7ac34bcb9473/jij.py#L52-L53
Namesto tega svetujem, da opozorila prikazujeta znotraj obstoječih predlog (potem se lahko tudi obrazci znova izpolnijo z vnesenimi podatki) - poglejte si, kako je to urejeno v vzorcu.

**Comment by ian-spiller** [comment]
Hvala za nasvet. Imam samo eno vprašanje, namreč kako lahko dobim v HTML parameter iz URLja torej če naredim redirect(url(prijava,parameter=parameter)) kako naj potem v prijavi dobim ven vrednost parametra?

**Comment by jaanos** [comment]
Parametri, ki jih lahko podaste pri funkciji `url`, so tisti, ki jih sprejme funkcija s podanim imenom. Kolikor vidim, trenutno nobena od vaših funkcij za poti ne sprejme parametra. Če bi na primer imeli funkcijo, kot je
```python
@get('/primer/<id:int>/')
def primer(id):
    ...
```
potem bi lahko ustrezen url zgradili npr. kot `url('primer', id=podatek)` in bi vrednost spremenljivke `podatek` v funkciji `primer` dobili v spremenljivko `id`.

**Comment by ian-spiller** [comment]
Najlepša hvala za razlago.
