### ISSUE TITLE
Končanje projekta

### ISSUE THREAD

**Issue by majbc1999** [ian-spiller/JIJ-prodaja-avtov#5]
Živjo! Janoš mi je sporočil, da nameravate kmalu končati projekt, zato sem malo pregledal za kakšne napake:

1.  Vsi redirecti, ki jih imate s funkcijo `url`, morajo v funkciji vsebovati ime funkcije iz `jij.py`, ne pa naslova. Na primer, vašo kodo:
```python
@post("/dodaj_administratorja")
def dodaj_administratorja():
    oseba=request.forms.get("oseba")
    cur.execute("UPDATE oseba SET administrator = 1 WHERE uporabnisko_ime = %s",(oseba,))
    baza.commit()
    redirect(url("/izbira_administrator"))
```
morate spremeniti v:
```python
@post("/dodaj_administratorja")
def dodaj_administratorja():
    oseba=request.forms.get("oseba")
    cur.execute("UPDATE oseba SET administrator = 1 WHERE uporabnisko_ime = %s",(oseba,))
    baza.commit()
    redirect(url('izbira_administrator'))
```

2. Ko boste to storili, morate dodati še `Binder` (če ne znate, si poglejte, kako so to storili pri https://github.com/nezakrzan/Nepremicninske-agencije).

3. Ostalo na strani dela dobro, vseeno pa bi rad še da nekje prikažete brisanje oz. spreminjanje podatkov v baze. Na primer, lahko implementirate, da je možno oglas izbrisati iz baze ali pa ga urediti. 

Ko boste naredili te tri zahteve, napišite, da vam čimprej pregledam in odobrim projekt za oddajo.

**Comment by ian-spiller** [comment]
Glede točke tri me samo zanima, ali ni dovolj že, če kot administrator lahko dodajate nove modele in znamke? Se opravičujem pozabil sem napisati, da če uporabite uporabniško ime ian in geslo ian za prijavo se vam bo odprla drugačna stran, kjer boste imeli tudi te možnosti.

**Comment by majbc1999** [comment]
Sem pogledal sedaj še to opcijo, vseeno manjka neko brisanje iz baze. Morda lahko za administratorja dodate še izbris modela ali znamke oz. spremembo (edit) modela ali znamke?

**Comment by ian-spiller** [comment]
Smo dodali še izbris modela, ali je tako bolje? Glede binderja pa mi ni jasno kako dobim drugi dve datoteki, saj nimata ne .txt končnice niti kakšne druge?

**Comment by majbc1999** [comment]
Izbris modela zgleda ok, vendar je problem, da mi ne deluje. Če želim recimo izbrisati Volkswagen Passat, ga potem še vedno ponudi pri objavljanju novega oglasa, pa tudi v obstoječih oglasih ostajajo vsi Passati. To morate še popraviti. Ostalo se mi sedaj zdi v redu.

Glede datotek `postBuild` in `start` imaš dve opciji:
- lahko odpreš `New file` v VS Codu, klikneš `Save as` in izbereš pod `Vrsta datoteke` opcijo `No extension (*.)`
- če ti to ne bo šlo, lahko kloniraš vzorčni repozitorij https://github.com/jaanos/OPB-bottle in copy-pastaš datoteki v svoj repozitorij

**Comment by ian-spiller** [comment]
Se opravičujem za nedelovanje Volkswagna mislim, da bi sedaj moralo delati. Dodal sem tudi binder.

**Comment by majbc1999** [comment]
Odlično, projekt sedaj dela dobro. Treba je samo še poskrbeti za Binder. Seveda je treba dodati v README link, ki nas pošlje na Binder:
```
[![bottle.py](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ian-spiller/JIJ-prodaja-avtov/main?urlpath=proxy/8080/)
```
Zaenkrat vam sicer Binderja ne požene pravilno, razlog pa je, da ste pozabili v datoteki `prijava.html` link brez uporabe funkcije `url`:
```html
    <div class="text-center pb-3 pt-3">  
        <a href="/registracija">Registracija</a>
    </div>
```
Poskusite popraviti, da vidimo, če vam potem uspešno požene Binder.

**Comment by ian-spiller** [comment]
Sem dodal url ampak mi še zmeraj ne dela binder.

**Comment by jaanos** [comment]
Da bo delovalo poganjanje na Binderju, bo potrebno v `jij.py` preberite privzete nastavitve iz okolja:
```python
import os
SERVER_PORT = os.environ.get('BOTTLE_PORT', 8080)
RELOADER = os.environ.get('BOTTLE_RELOADER', True)
DB_PORT = os.environ.get('POSTGRES_PORT', 5432)
```
in jih uporabite pri povezavi na bazo in poganjanju strežnika:
```python
baza = psycopg2.connect(database=dbname, host=host, user=user, password=password, port=DB_PORT)
run(host='localhost', port=SERVER_PORT, reloader=RELOADER)
```

Svetujem še, da v `README.md` dodaste kratka navodila za uporabo (npr. zgoraj omenjeno uporabniško ime in geslo za administratorja).

**Comment by ian-spiller** [comment]
Najlepša hvala za pomoč. Mislim, da sedaj vse deluje v READ.md pa sem tudi dodal navodila.

**Comment by jaanos** [comment]
Binder sedaj deluje. Sem se pa prijavil kot nov uporabnik in vidim, da stvari več ne delujejo. Kot vidim, je težava v tem, da poskušate v piškotku `id_uporabnika` hraniti urejen par, a piškotki lahko hranijo le nize - tako pri pridobivanju ID-ja iz piškotka vzamete samo prvo številko ID-ja. Svetujem torej, da imate v `id_uporabnika` shranjen ID (tako ne bo potrebno indeksirati in boste lahko pridobili celoten ID), podatek o tem, ali je uporabnik administrator, pa hranite v ločenem piškotku.

Glede na to, da se lahko zgodi, da kakšna poizvedba ne uspe, je treba poskrbeti še za to, da zaradi tega aplikacija ne bo nehala delovati. Da to naredite, bo potrebno preklicati transakcijo ob neuspešni poizvedbi. Registracijo lahko torej naredite tako:
```python
try:
    cur.execute("""
        INSERT INTO oseba (ime, id_zavarovalnice, telefon, geslo, uporabnisko_ime, administrator) 
        VALUES(%(ime)s, %(zav)s, %(tel)s, %(geslo)s, %(uporabnisko_ime)s, %(administrator)s)
        RETURNING id
    """, {"ime": ime,"zav": id_zav, "tel": tel, "geslo": geslo, "uporabnisko_ime": uporabnisko_ime, "administrator": 0})
    id_uporabnika, = cur.fetchone() # poizvedba vrne generirani ID in ga tako ni potrebno pridobiti z novo poizvedbo
    response.set_cookie("id_uporabnika", id_uporabnika, secret=skrivnost)
    response.set_cookie("administrator", 0, secret=skrivnost)
    baza.commit()
except psycopg2.DatabaseError:
    baza.rollback()
    # karkoli želite narediti ob napaki, npr. prikažete izpolnjen obrazec z obvestilom o napaki
```
Podobno naredite še pri drugih poizvedbah, ki spreminjajo bazo.

Mimogrede, za telefonsko številko predlagam, da imate kar stolpec tipa `TEXT`, saj se te običajno začnejo z ničlo in lahko vsebujejo tudi kakšne neštevilske znake (tako jih ne pretvarjajte v cela števila). Opažam še, da v tabeli `modeli` nimate glavnega ključa - lahko bi to bila kar oba stolpca, še bolje pa bo, da jima daste določilo `UNIQUE` in dodaste še en stolpec z ID-jem (ki bo seveda glavni ključ). Potem se lahko v tabeli `oglas` sklicujete kar na ID modela (in tako ne rabite posebej še ID-ja znamke).

Še to: metoda `request.forms.get` ima težave s kodiranjem znakov. Da se izognete težavam, namesto npr. `request.forms.get('uporabnisko_ime')` uporabite `request.forms.uporabnisko_ime`. Svetujem tudi, da se pri neuspešni registraciji/vnosu oglasa/... obrazec izpolni s predhodno vpisanimi podatki.

**Comment by ian-spiller** [comment]
Vredu bomo popravili. Kako pa dosežemo, da vrnemo izpolnjen obrazec?

**Comment by ian-spiller** [comment]
Cookie smo popravili prav tako smo dodali try in except funkcijo in spremenili request.forms, edino težave imamo s  vračanjem izpolnjenega obrazca. Prosil vas bi, če lahko uporabimo prvi način pri spreminjanju tabele modeli, saj se na znamke navezujejo serviserji in posledično zavarovanlice in bi bilo potrebno spremeniti zelo velik del programa.

**Comment by ian-spiller** [comment]
Oziroma težave s vračanjem izpolnjenega obrazca so samo še takrat kadar uporabljamo select v HTML-ju.

**Comment by jaanos** [comment]
Za `select` lahko naredite tako:
```html
            <select class="form-select" name="zav" id="zav">
                %for id, zavarovalnica in a:
                    <option value="{{id}}" {{'selected' if id == zav else ''}}>{{zavarovalnica}}</option>
                %end
            </select>
```

**Comment by jaanos** [comment]
Mimogrede, sedaj, ko ste popravili pridobivanje iz `request.forms`, prekodiranje (ISO-8859-1/UTF-8) ni več potrebno (vam bo kvečjemu povzročalo težave). Za privzeto zavarovalnico pa raje uporabite kar `None` (tj., brez privzett izbire), saj nimate zagotovila, da bo obstajala zavarovalnica z ID-jem 1 (tj., morda se enkra pobriše).

**Comment by ian-spiller** [comment]
Smo popravili kodiranje in nastavili privzeto zavarovalnico na None samo select pa nam še zmeraj ne izpolni obrazca.

**Comment by jaanos** [comment]
Mislim, da bo zdaj v redu, tako da bom dodal povezavo do projekta na repozitorij predmeta. Če se še niste, se lahko torej z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Opomnil bi le še to, da geslo v bazi hranite v čisti obliki. Svetujem, da namesto tega uporabite njegovo zgostitev - poglejte si, kako je to narejeno pri že oddanih projektih.

**Comment by ian-spiller** [comment]
Najlepša hvala. Smo popravili tudi gesla.

**Comment by jaanos** [comment]
Sem posodobil povezavo. Sem pa opazil, da brisanje modela ne deluje, če vsebuje posebne znake, saj še vedno uporabljate metodo `request.forms.get`. Prav tako lahko vsak uporabnik dostopa do administratorskih strani, če pozna poti do njih. Da to preprečite, pred njihovim prikazom preverite ustrezni piškotek in uporabnika preusmerite, če ni administrator.

**Comment by jaanos** [comment]
Lahko uporabite npr.
```python
getattr(request.forms, "model{}".format(znamka))
```
Sicer pa imena polj v obrazcih s spremenljivimi/sestavljenimi imeni načeloma niso najboljša ideja. Kot rečeno, bi bilo bolje, če bi vsak model imel svoj ID, pa bi potem imeli en izbirnik za model, ki bi ga polnili z Javascriptom glede na izbrano znamko. Potem bi v obrazcu poslali samo ID modela in tega vstavili v bazo.

**Comment by ian-spiller** [comment]
Najlepša hvala za pomoč. Si bomo zapomnili in naslednjič definitivno naredili tako kot ste predlagali.

**Comment by jaanos** [comment]
Velja - bom posodobil povezavo, da bo kazala na zadnji commit.
